version: '3'

services:
  nginx:
    container_name: nginx-lemp
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
  php:
    container_name: php-lemp
    build: ./php
    restart: unless-stopped
    volumes:
      - ./html/:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db
  db:
    container_name: mariadb-lemp
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      # - ./mariadb/initdb/:/docker-entrypoint-initdb.d
      - ./mariadb/data/:/var/lib/mysql
    environment:
      # - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=passsword